services:
  - type: web
    name: ghibli-style-bot
    env: python
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URL
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PORT
        value: 10000
